language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
script:
  - npm test
  - npm run build
after_success:
  - npm run travis-deploy-once
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run travis-deploy-once "npm run semantic-release"; fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
